### ISSUE TITLE
"chmod: cannot access '/data/data/com.termux/files/usr/tmp/termuc/main': No such file or directory" when run the compiled file

### ISSUE THREAD

**Issue by GWLGT** [RainbowC0/TermuC#12]
Hello!, I'm first time use this App, i try to compile the .cpp file, it gone well, but when i try to run it, it says:

```log
chmod: cannot access '/data/data/com.termux/files/usr/tmp/termuc/main': No such file or directory
```

when i check that directory, the file "main" indeed doesn't exist, why? i already check all the thing needed such as permission, everything is right, anyone help with this?

**Comment by RainbowC0** [comment]
The project-managing function is not so well completed. In app/src/main/java/cn.rbc.termuc/MainActivity.java:onMenuItemClick:

```java
sb = Project.buildEnvironment(f);
sb.append("exec=$TMPDIR/termuc;mkdir $exec 2>/dev/null;find $o -maxdepth 1 -type f \\( -iname '*.so' -o ! -name '*.*' \\) -exec cp {} $exec \\;;exec=$exec/");
b.append(Project.runCmd);
sb.append(" && chmod +x $exec && ");
```
it try to make the $TMPDIR/termuc first (/data/data/com.termux/files/tmp/termuc), and then find all executable files in $o directory (the `outputDir` configured in `termuc.json`) and copy to the $exec.

The most likely reason is that the `find $o -maxdepth 1 -type f \( -iname '*.so' ! -name '*.*' \)` command does not find the `main` file. Mightly you have not installed `findutils` in Termux.

You can also check the termuc.json file in your project, make sure that the `buildCmd` would output the executable file in the $o (`outputDir`).

**Comment by RainbowC0** [comment]
You should `build` the project instead of compile it. The compile function would generate the object file (.o) instead of an ELF file. Please view the `termuc.json` file under your project's root.

**Comment by GWLGT** [comment]
thanks, I'll read the config file more careful next time, anyway, great project tho.

**Comment by GWLGT** [comment]
but i also noticed that when i type quote or braces, it doesn't automatically close it
