### ISSUE TITLE
Offline me

### ISSUE THREAD

**Issue by HanzoDev1375** [RainbowC0/TermuC#2]
hello download gcc offline using why using termux?

**Comment by RainbowC0** [comment]
Termux is a terminal environment like Unix. It's easy for us to deploy a developing environment. We can install gcc in Termux by following commands:

    ~$ pkg i clang

**In fact, Termux support clang compiler originally and offer `gcc` command as an alias to clang**. Then run `gcc -v` to confirm if gcc is installed successfully:
```
~$ gcc -v
clang version 18.1.2
Target: aarch64-unknown-linux-android24
Thread model: posix
InstalledDir: /data/data/com.termux/files/usr/bin
```

Thanks for the reminder! I will switch to the clang/clang++ command as the compiler in a future update.
